// Copyright 2018 the u-root Authors. All rights reserved
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"strings"

	"github.com/9elements/txt-suite/pkg/api"
)

// CPU Check Blacklist Data
type brandNameMetaBl struct {
	xeon    bool
	pentium bool
	core    bool
	atom    bool
	celeron bool
	itanium bool
	name    string
}

// CPU Black list
var (
	TXTUnSupportedCPUs []brandNameMetaBl = []brandNameMetaBl{
		{false, false, false, false, true, false, "310 "},
		{false, false, false, false, true, false, "315 "},
		{false, false, false, false, true, false, "315J "},
		{false, false, false, false, true, false, "320 "},
		{false, false, false, false, true, false, "325 "},
		{false, false, false, false, true, false, "325J "},
		{false, false, false, false, true, false, "326 "},
		{false, false, false, false, true, false, "330 "},
		{false, false, false, false, true, false, "330J "},
		{false, false, false, false, true, false, "331 "},
		{false, false, false, false, true, false, "335 "},
		{false, false, false, false, true, false, "335J "},
		{false, false, false, false, true, false, "336 "},
		{false, false, false, false, true, false, "340 "},
		{false, false, false, false, true, false, "340J "},
		{false, false, false, false, true, false, "341 "},
		{false, false, false, false, true, false, "345 "},
		{false, false, false, false, true, false, "345J "},
		{false, false, false, false, true, false, "346 "},
		{false, false, false, false, true, false, "350 "},
		{false, false, false, false, true, false, "350J "},
		{false, false, false, false, true, false, "351 "},
		{false, false, false, false, true, false, "352 "},
		{false, false, false, false, true, false, "355 "},
		{false, false, false, false, true, false, "356 "},
		{false, false, false, false, true, false, "360 "},
		{false, false, false, false, true, false, "310 "},
		{false, false, false, false, true, false, "320 "},
		{false, false, false, false, true, false, "330 "},
		{false, false, false, false, true, false, "340 "},
		{false, false, false, false, true, false, "350 "},
		{false, false, false, false, true, false, "360 "},
		{false, false, false, false, true, false, "370 "},
		{false, false, false, false, true, false, "380 "},
		{false, false, false, false, true, false, "390 "},
		{false, false, false, false, true, false, "410 "},
		{false, false, false, false, true, false, "420 "},
		{false, false, false, false, true, false, "430 "},
		{false, false, false, false, true, false, "440 "},
		{false, false, false, false, true, false, "450 "},
		{false, false, false, false, true, false, "333 "},
		{false, false, false, false, true, false, "353 "},
		{false, false, false, false, true, false, "373 "},
		{false, false, false, false, true, false, "383 "},
		{false, false, false, false, true, false, "423 "},
		{true, false, false, false, false, false, "3040 "},
		{true, false, false, false, false, false, "3050 "},
		{true, false, false, false, false, false, "3060 "},
		{true, false, false, false, false, false, "3070 "},
		{true, false, false, false, false, false, "5030 "},
		{true, false, false, false, false, false, "5040 "},
		{true, false, false, false, false, false, "5050 "},
		{true, false, false, false, false, false, "5060 "},
		{true, false, false, false, false, false, "5070 "},
		{true, false, false, false, false, false, "5080 "},
		{true, false, false, false, false, false, "5110 "},
		{true, false, false, false, false, false, "5120 "},
		{true, false, false, false, false, false, "5130 "},
		{true, false, false, false, false, false, "5140 "},
		{true, false, false, false, false, false, "5150 "},
		{true, false, false, false, false, false, "5160 "},
		{true, false, false, false, false, false, "5148 "},
		{true, false, false, false, false, false, "7020 "},
		{true, false, false, false, false, false, "7030 "},
		{true, false, false, false, false, false, "7040 "},
		{true, false, false, false, false, false, "7041 "},
		{false, false, true, false, false, false, "L2300 "},
		{false, false, true, false, false, false, "L2400 "},
		{false, false, true, false, false, false, "L2500 "},
		{false, false, true, false, false, false, "T2050 "},
		{false, false, true, false, false, false, "T2250 "},
		{false, false, true, false, false, false, "T2300 "},
		{false, false, true, false, false, false, "T2300E "},
		{false, false, true, false, false, false, "T2400 "},
		{false, false, true, false, false, false, "T2500 "},
		{false, false, true, false, false, false, "T2600 "},
		{false, false, true, false, false, false, "T2700 "},
		{false, false, true, false, false, false, "U2400 "},
		{false, false, true, false, false, false, "U2500 "},
		{false, false, true, false, false, false, "T1300 "},
		{false, false, true, false, false, false, "T1350 "},
		{false, false, true, false, false, false, "T1400 "},
		{false, false, true, false, false, false, "U1300 "},
		{false, false, true, false, false, false, "U1400 "},
		{false, false, true, false, false, false, "E6300 "},
		{false, false, true, false, false, false, "E6400 "},
		{false, false, true, false, false, false, "E6600 "},
		{false, false, true, false, false, false, "E6700 "},
		{false, false, true, false, false, false, "T5200 "},
		{false, false, true, false, false, false, "T5500 "},
		{false, false, true, false, false, false, "T5600 "},
		{false, false, true, false, false, false, "T7200 "},
		{false, false, true, false, false, false, "T7400 "},
		{false, false, true, false, false, false, "T7600 "},
		{false, false, true, false, false, false, "X6800 "},
		{true, false, false, false, false, false, "7110M "},
		{true, false, false, false, false, false, "7110N "},
		{true, false, false, false, false, false, "7120M "},
		{true, false, false, false, false, false, "7120N "},
		{true, false, false, false, false, false, "7130M "},
		{true, false, false, false, false, false, "7130N "},
		{true, false, false, false, false, false, "7140M "},
		{true, false, false, false, false, false, "7140N "},
		{false, true, false, false, false, false, "518 "},
		{false, true, false, false, false, false, "532 "},
		{false, true, false, false, false, false, "538 "},
		{false, true, false, false, false, false, "548 "},
		{false, true, false, false, false, false, "552 "},
		{false, true, false, false, false, false, "517 "},
		{false, true, false, false, false, false, "520 "},
		{false, true, false, false, false, false, "521 "},
		{false, true, false, false, false, false, "530 "},
		{false, true, false, false, false, false, "531 "},
		{false, true, false, false, false, false, "540 "},
		{false, true, false, false, false, false, "541 "},
		{false, true, false, false, false, false, "550 "},
		{false, true, false, false, false, false, "551 "},
		{false, true, false, false, false, false, "560 "},
		{false, true, false, false, false, false, "561 "},
		{false, true, false, false, false, false, "570 "},
		{false, true, false, false, false, false, "571 "},
		{false, true, false, false, false, false, "630 "},
		{false, true, false, false, false, false, "631 "},
		{false, true, false, false, false, false, "640 "},
		{false, true, false, false, false, false, "641 "},
		{false, true, false, false, false, false, "650 "},
		{false, true, false, false, false, false, "651 "},
		{false, true, false, false, false, false, "660 "},
		{false, true, false, false, false, false, "661 "},
		{false, true, false, false, false, false, "662 "},
		{false, true, false, false, false, false, "670 "},
		{false, true, false, false, false, false, "672 "},
		{false, true, false, false, false, false, "805 "},
		{false, true, false, false, false, false, "820 "},
		{false, true, false, false, false, false, "830 "},
		{false, true, false, false, false, false, "840 "},
		{false, true, false, false, false, false, "915 "},
		{false, true, false, false, false, false, "920 "},
		{false, true, false, false, false, false, "925 "},
		{false, true, false, false, false, false, "930 "},
		{false, true, false, false, false, false, "940 "},
		{false, true, false, false, false, false, "945 "},
		{false, true, false, false, false, false, "950 "},
		{false, true, false, false, false, false, "960 "},
		{false, true, false, false, false, false, "705 "},
		{false, true, false, false, false, false, "715 "},
		{false, true, false, false, false, false, "725 "},
		{false, true, false, false, false, false, "730 "},
		{false, true, false, false, false, false, "735 "},
		{false, true, false, false, false, false, "740 "},
		{false, true, false, false, false, false, "745 "},
		{false, true, false, false, false, false, "745A "},
		{false, true, false, false, false, false, "750 "},
		{false, true, false, false, false, false, "755 "},
		{false, true, false, false, false, false, "760 "},
		{false, true, false, false, false, false, "765 "},
		{false, true, false, false, false, false, "770 "},
		{false, true, false, false, false, false, "780 "},
		{false, true, false, false, false, false, "718 "},
		{false, true, false, false, false, false, "738 "},
		{false, true, false, false, false, false, "758 "},
		{false, true, false, false, false, false, "778 "},
		{false, true, false, false, false, false, "713 "},
		{false, true, false, false, false, false, "723 "},
		{false, true, false, false, false, false, "733 "},
		{false, true, false, false, false, false, "753 "},
		{false, true, false, false, false, false, "773 "},
		{false, true, false, false, false, false, "840 "},
		{false, true, false, false, false, false, "955 "},
		{false, true, false, false, false, false, "965 "},
		{false, false, false, false, true, false, "347 "},
		{false, false, false, false, true, false, "365 "},
		{false, false, false, false, true, false, "520 "},
		{false, false, false, false, true, false, "443 "},
		{false, false, false, false, false, true, "9010 "},
		{false, false, false, false, false, true, "9015 "},
		{false, false, false, false, false, true, "9020 "},
		{false, false, false, false, false, true, "9030 "},
		{false, false, false, false, false, true, "9040 "},
		{false, false, false, false, false, true, "9050 "},
		{false, true, false, false, false, false, "935 "},
		{true, false, false, false, false, false, "5063 "},
		{false, true, false, false, false, false, "T2060 "},
		{false, false, true, false, false, false, "U1500 "},
		{false, false, true, false, false, false, "E4300 "},
		{false, false, true, false, false, false, "L7200 "},
		{false, false, true, false, false, false, "L7400 "},
		{false, false, true, false, false, false, "QX6700 "},
		{true, false, false, false, false, false, "7150N "},
		{true, false, false, false, false, false, "E5310 "},
		{true, false, false, false, false, false, "E5320 "},
		{true, false, false, false, false, false, "E5345 "},
		{true, false, false, false, false, false, "X3210 "},
		{true, false, false, false, false, false, "X3220 "},
		{true, false, false, false, false, false, "X5355 "},
		{true, false, false, false, false, false, "E5335 "},
		{false, false, false, false, true, false, "530 "},
		{false, false, false, false, true, false, "420 "},
		{false, false, false, false, true, false, "430 "},
		{false, false, false, false, true, false, "440 "},
		{false, true, false, false, false, false, "E2140 "},
		{false, true, false, false, false, false, "E2160 "},
		{false, true, false, false, false, false, "T2080 "},
		{false, false, true, false, false, false, "T2350 "},
		{false, false, true, false, false, false, "T2450 "},
		{false, false, true, false, false, false, "E4400 "},
		{false, false, true, false, false, false, "E6320 "},
		{false, false, true, false, false, false, "E6420 "},
		{false, false, true, false, false, false, "L7300 "},
		{false, false, true, false, false, false, "L7500 "},
		{false, false, true, false, false, false, "T5300 "},
		{false, false, true, false, false, false, "T7100 "},
		{false, false, true, false, false, false, "T7300 "},
		{false, false, true, false, false, false, "T7500 "},
		{false, false, true, false, false, false, "T7700 "},
		{false, false, true, false, false, false, "U7500 "},
		{false, false, true, false, false, false, "U7600 "},
		{false, false, true, false, false, false, "Q6600 "},
		{true, false, false, false, false, false, "L5320 "},
		{true, false, false, false, false, false, "L5310 "},
		{true, false, false, false, false, false, "5128 "},
		{true, false, false, false, false, false, "5133 "},
		{true, false, false, false, false, false, "5138 "},
		{true, false, false, false, false, false, "X5365 "},
		{false, false, true, false, false, false, "QX6800 "},
		{false, true, false, false, false, false, "T2130 "},
		{false, false, false, false, true, false, "540 "},
		{true, false, false, false, false, false, "5113 "},
		{true, false, false, false, false, false, "E7210 "},
		{true, false, false, false, false, false, "E7220 "},
		{false, false, true, false, false, false, "E4500 "},
		{false, false, true, false, false, false, "E6540 "},
		{false, false, true, false, false, false, "T5250 "},
		{false, false, true, false, false, false, "T5450 "},
		{false, false, true, false, false, false, "X7800 "},
		{false, false, true, false, false, false, "QX6850 "},
		{false, false, true, false, false, false, "Q6700 "},
		{true, false, false, false, false, false, "E7310 "},
		{true, false, false, false, false, false, "E7320 "},
		{true, false, false, false, false, false, "E7330 "},
		{true, false, false, false, false, false, "E7340 "},
		{true, false, false, false, false, false, "X7350 "},
		{true, false, false, false, false, false, "X3230 "},
		{false, false, false, false, true, false, "550 "},
		{false, false, true, false, false, false, "T7250 "},
		{false, false, true, false, false, false, "T7800 "},
		{false, false, true, false, false, false, "X7900 "},
		{false, false, false, false, false, true, "9150M "},
		{false, true, false, false, false, false, "E2180 "},
		{false, false, true, false, false, false, "T5470 "},
		{false, false, true, false, false, false, "U2100 "},
		{false, false, true, false, false, false, "U2200 "},
		{false, false, false, false, false, true, "9110N "},
		{false, false, false, false, false, true, "9120N "},
		{false, false, false, false, false, true, "9130M "},
		{false, false, false, false, false, true, "9140M "},
		{false, false, false, false, false, true, "9140N "},
		{false, false, false, false, false, true, "9150N "},
		{true, false, false, false, false, false, "L7345 "},
		{false, false, false, false, true, false, "523 "},
		{false, false, true, false, false, false, "E4600 "},
		{false, false, true, false, false, false, "L7700 "},
		{false, false, true, false, false, false, "T5550 "},
		{false, true, false, false, false, false, "E2220 "},
		{false, true, false, false, false, false, "T2310 "},
		{false, true, false, false, false, false, "T2330 "},
		{true, false, false, false, false, false, "E5405 "},
		{true, false, false, false, false, false, "E5410 "},
		{true, false, false, false, false, false, "E5430 "},
		{true, false, false, false, false, false, "E5440 "},
		{true, false, false, false, false, false, "E5450 "},
		{true, false, false, false, false, false, "E5462 "},
		{true, false, false, false, false, false, "E5472 "},
		{true, false, false, false, false, false, "X5460 "},
		{true, false, false, false, false, false, "X5482 "},
		{true, false, false, false, false, false, "L5410 "},
		{true, false, false, false, false, false, "L5430 "},
		{true, false, false, false, false, false, "E5205 "},
		{false, false, true, false, false, false, "T5270 "},
		{false, false, true, false, false, false, "T8300 "},
		{false, false, false, false, true, false, "530 "},
		{false, false, false, false, true, false, "220 "},
		{true, false, false, false, false, false, "X5260 "},
		{true, false, false, false, false, false, "X5272 "},
		{false, false, true, false, false, false, "T5750 "},
		{false, false, true, false, false, false, "T8100 "},
		{false, false, true, false, false, false, "T9300 "},
		{false, false, true, false, false, false, "T9500 "},
		{false, false, true, false, false, false, "U7700 "},
		{false, false, true, false, false, false, "QX9650 "},
		{false, true, false, false, false, false, "E2200 "},
		{true, false, false, false, false, false, "E5420 "},
		{true, false, false, false, false, false, "L5420 "},
		{true, false, false, false, false, false, "X3320 "},
		{true, false, false, false, false, false, "X3350 "},
		{true, false, false, false, false, false, "X3360 "},
		{false, false, false, false, true, false, "560 "},
		{false, false, false, false, true, false, "E1200 "},
		{false, false, true, false, false, false, "E4700 "},
		{false, false, true, false, false, false, "X9000 "},
		{false, false, true, false, false, false, "QX9770 "},
		{false, true, false, false, false, false, "T2370 "},
		{true, false, false, false, false, false, "X5450 "},
		{true, false, false, false, false, false, "X5472 "},
		{false, false, false, false, false, true, "9152M "},
		{false, false, true, false, false, false, "QX9775 "},
		{true, false, false, false, false, false, "E3110 "},
		{true, false, false, false, false, false, "L5408 "},
		{true, false, false, false, false, false, "L5238 "},
		{true, false, false, false, false, false, "E5240 "},
		{false, false, false, false, true, false, "E1600 "},
		{false, false, true, false, false, false, "E6405 "},
		{false, false, false, false, true, false, "E1500 "},
		{false, false, false, false, true, false, "E1400 "},
		{true, false, false, false, false, false, "L5318 "},
		{true, false, false, false, false, false, "L5240 "},
		{false, true, false, false, false, false, "T2390 "},
		{false, false, true, false, false, false, "T5670 "},
		{false, false, false, false, true, false, "450 "},
		{false, false, true, false, false, false, "E6305 "},
		{false, false, false, false, true, false, "445 "},
		{true, false, false, false, false, false, "X3353 "},
		{true, false, false, false, false, false, "X3363 "},
		{false, true, false, false, false, false, "E5300 "},
		{true, false, false, false, false, false, "E3113 "},
		{true, false, false, false, false, false, "X3323 "},
		{false, false, true, false, false, false, "E7200 "},
		{true, false, false, false, false, false, "E3120 "},
		{true, false, false, false, false, false, "X5470 "},
		{false, false, true, false, false, false, "X9100 "},
		{true, false, false, false, false, false, "X3330 "},
		{true, false, false, false, false, false, "X3370 "},
		{false, false, false, true, false, false, "Z540 "},
		{false, false, false, true, false, false, "Z530 "},
		{false, false, false, true, false, false, "Z520 "},
		{false, false, false, true, false, false, "Z510 "},
		{false, false, false, true, false, false, "Z500 "},
		{false, false, true, false, false, false, "T5800 "},
		{false, true, false, false, false, false, "T3400 "},
		{false, false, false, true, false, false, "230 "},
		{false, false, false, true, false, false, "330 "},
		{false, false, false, true, false, false, "N270 "},
		{false, false, true, false, false, false, "E7300 "},
		{false, true, false, false, false, false, "E2210 "},
		{false, false, true, false, false, false, "E7400 "},
		{false, false, true, false, false, false, "E7500 "},
		{false, false, true, false, false, false, "Q8200 "},
		{true, false, false, false, false, false, "E5220 "},
		{true, false, false, false, false, false, "X5270 "},
		{false, false, false, false, true, false, "570 "},
		{false, false, false, false, true, false, "575 "},
		{false, false, false, false, true, false, "585 "},
		{true, false, false, false, false, false, "L5215 "},
		{false, false, false, false, true, false, "723 "},
		{false, false, true, false, false, false, "QX9300 "},
		{false, false, false, false, true, false, "722 "},
		{false, false, true, false, false, false, "P7350 "},
		{true, false, false, false, false, false, "L3014 "},
		{true, false, false, false, false, false, "X5492 "},
		{true, false, false, false, false, false, "L7445 "},
		{true, false, false, false, false, false, "L7455 "},
		{true, false, false, false, false, false, "E7430 "},
		{true, false, false, false, false, false, "E7450 "},
		{true, false, false, false, false, false, "E7440 "},
		{true, false, false, false, false, false, "E7420 "},
		{true, false, false, false, false, false, "X7460 "},
		{false, false, true, false, false, false, "T5870 "},
		{true, false, false, false, false, false, "E5502 "},
		{true, false, false, false, false, false, "E5503 "},
		{true, false, false, false, false, false, "E5506 "},
		{true, false, false, false, false, false, "E5507 "},
		{true, false, false, false, false, false, "E5530 "},
		{true, false, false, false, false, false, "E5540 "},
		{true, false, false, false, false, false, "X5550 "},
		{true, false, false, false, false, false, "X5560 "},
		{true, false, false, false, false, false, "X5570 "},
		{true, false, false, false, false, false, "W5580 "},
		{false, false, true, false, false, false, "P7370 "},
		{false, false, false, false, true, false, "T1700 "},
		{false, false, false, false, true, false, "743 "},
		{false, false, true, false, false, false, "i7-920 "},
		{false, false, true, false, false, false, "i7-940 "},
		{false, false, true, false, false, false, "i7-965 "},
		{false, false, true, false, false, false, "i7-950 "},
		{false, false, true, false, false, false, "i7-960 "},
		{false, false, true, false, false, false, "i7-975 "},
		{false, false, true, false, false, false, "Q9500 "},
		{false, true, false, false, false, false, "T3200 "},
		{false, true, false, false, false, false, "E5200 "},
		{false, false, true, false, false, false, "T1250 "},
		{false, true, false, false, false, false, "T4200 "},
		{false, true, false, false, false, false, "T4300 "},
		{false, false, true, false, false, false, "T6600 "},
		{false, false, false, false, true, false, "T3100 "},
		{false, false, true, false, false, false, "Q8400 "},
		{false, false, false, false, true, false, "T1600 "},
		{false, false, true, false, false, false, "Q8300 "},
		{true, false, false, false, false, false, "W3520 "},
		{true, false, false, false, false, false, "W3540 "},
		{true, false, false, false, false, false, "W3550 "},
		{true, false, false, false, false, false, "W3565 "},
		{true, false, false, false, false, false, "W3570 "},
		{true, false, false, false, false, false, "W3580 "},
		{true, false, false, false, false, false, "E5520 "},
		{true, false, false, false, false, false, "L5520 "},
		{false, true, false, false, false, false, "E5400 "},
		{false, false, true, false, false, false, "T6400 "},
		{true, false, false, false, false, false, "E5504 "},
		{true, false, false, false, false, false, "L5506 "},
		{true, false, false, false, false, false, "L5508 "},
		{true, false, false, false, false, false, "L5518 "},
		{false, false, false, false, true, false, "T3000 "},
		{false, true, false, false, false, false, "T4400 "},
		{false, false, false, true, false, false, "Z515 "},
		{false, false, false, true, false, false, "Z550 "},
		{true, false, false, false, false, false, "W3503 "},
		{true, false, false, false, false, false, "W3505 "},
		{false, false, true, false, false, false, "Q8200S "},
		{true, false, false, false, false, false, "X3380 "},
		{false, false, false, true, false, false, "Z530P "},
		{false, false, false, true, false, false, "Z520PT "},
		{false, false, false, true, false, false, "Z510P "},
		{false, false, false, true, false, false, "Z510PT "},
		{true, false, false, false, false, false, "W3530 "},
		{false, false, false, false, true, false, "573 "},
		{false, false, false, true, false, false, "N280 "},
		{false, false, true, false, false, false, "i7-930 "},
		{false, true, false, false, false, false, "E6300 "},
		{false, false, true, false, false, false, "E7600 "},
		{false, false, false, false, true, false, "900 "},
		{true, false, false, false, false, false, "W5590 "},
		{true, false, false, false, false, false, "L5530 "},
		{false, true, false, false, false, false, "SU2700 "},
		{false, false, true, false, false, false, "Q8400S "},
		{false, true, false, false, false, false, "920 "},
		{false, false, true, false, false, false, "P7570 "},
		{false, false, false, true, false, false, "N450 "},
		{false, false, false, false, true, false, "E3200 "},
		{false, false, false, false, true, false, "E3300 "},
		{false, false, false, false, true, false, "E3400 "},
		{false, false, false, false, true, false, "E3500 "},
		{false, false, false, false, true, false, "SU2300 "},
		{false, false, true, false, false, false, "SU7300 "},
		{false, true, false, false, false, false, "E5500 "},
		{false, true, false, false, false, false, "E5700 "},
		{false, true, false, false, false, false, "E5800 "},
		{false, true, false, false, false, false, "E6500 "},
		{false, true, false, false, false, false, "E6500K "},
		{false, true, false, false, false, false, "E6600 "},
		{false, true, false, false, false, false, "E6700 "},
		{false, true, false, false, false, false, "E6800 "},
		{false, false, true, false, false, false, "i5-750 "},
		{false, false, true, false, false, false, "i5-750S "},
		{false, true, false, false, false, false, "T4500 "},
		{false, false, false, true, false, false, "D510 "},
		{false, true, false, false, false, false, "G6950 "},
		{false, false, false, true, false, false, "D410 "},
		{false, false, false, false, true, false, "G1101 "},
		{false, false, true, false, false, false, "i3-350M "},
		{false, false, true, false, false, false, "i5-430M "},
		{false, false, true, false, false, false, "i5-661 "},
		{false, true, false, false, false, false, "G6951 "},
		{false, true, false, false, false, false, "SU4100 "},
		{false, false, false, true, false, false, "N470 "},
		{false, false, true, false, false, false, "i3-530 "},
		{false, false, true, false, false, false, "i3-540 "},
		{false, true, false, false, false, false, "G6960 "},
		{false, false, false, false, true, false, "T3300 "},
		{false, false, false, false, true, false, "P4500 "},
		{false, false, true, false, false, false, "i3-330M "},
		{false, false, true, false, false, false, "i7-980X "},
		{false, false, true, false, false, false, "i7-970 "},
		{false, false, true, false, false, false, "i3-330E "},
		{false, false, false, false, true, false, "P4505 "},
		{false, false, true, false, false, false, "i5-760 "},
		{false, false, true, false, false, false, "i7-875K "},
		{false, false, true, false, false, false, "i3-550 "},
		{false, false, true, false, false, false, "i5-655K "},
		{false, false, true, false, false, false, "i3-370M "},
		{false, false, true, false, false, false, "i3-330UM "},
		{false, false, true, false, false, false, "i5-450M "},
		{false, false, true, false, false, false, "i5-430UM "},
		{false, true, false, false, false, false, "P6000 "},
		{false, true, false, false, false, false, "U5400 "},
		{false, false, false, false, true, false, "U3400 "},
		{false, false, false, true, false, false, "D425 "},
		{false, false, false, true, false, false, "D525 "},
		{false, false, false, true, false, false, "N455 "},
		{false, false, false, true, false, false, "N475 "},
		{false, false, false, true, false, false, "Z600 "},
		{false, false, false, true, false, false, "Z615 "},
		{false, false, false, true, false, false, "Z625 "},
		{false, false, false, true, false, false, "Z560 "},
		{false, false, true, false, false, false, "i5-470UM "},
		{false, false, true, false, false, false, "i3-380UM "},
		{false, true, false, false, false, false, "U5600 "},
		{false, false, false, false, true, false, "U3600 "},
		{false, false, false, true, false, false, "N550 "},
		{false, false, false, false, true, false, "U3405 "},
		{false, true, false, false, false, false, "P6100 "},
		{false, true, false, false, false, false, "P6200 "},
		{false, false, true, false, false, false, "i3-560 "},
		{false, false, true, false, false, false, "i3-380M "},
		{false, false, true, false, false, false, "i5-460M "},
		{false, true, false, false, false, false, "P6300 "},
		{false, false, true, false, false, false, "i5-2300 "},
		{false, false, true, false, false, false, "i5-2500K "},
		{false, false, true, false, false, false, "i7-2600K "},
		{false, false, true, false, false, false, "i7-2630QM "},
		{false, false, true, false, false, false, "i3-2310M "},
		{false, false, true, false, false, false, "i5-2410M "},
		{false, false, false, false, true, false, "P4600 "},
		{false, false, false, true, false, false, "E620 "},
		{false, false, false, true, false, false, "E620T "},
		{false, false, false, true, false, false, "E640 "},
		{false, false, false, true, false, false, "E640T "},
		{false, false, false, true, false, false, "E660 "},
		{false, false, false, true, false, false, "E660T "},
		{false, false, false, true, false, false, "E680 "},
		{false, false, false, true, false, false, "E680T "},
		{false, false, true, false, false, false, "i7-990X "},
		{false, false, true, false, false, false, "i5-480M "},
		{false, false, true, false, false, false, "i3-390M "},
		{false, false, false, false, true, false, "G530 "},
		{false, false, false, false, true, false, "G530T "},
		{false, false, false, false, true, false, "G540 "},
		{false, false, false, false, true, false, "G540T "},
		{false, false, false, false, true, false, "G550 "},
		{false, false, false, false, true, false, "G550T "},
		{false, false, true, false, false, false, "i3-2100 "},
		{false, false, true, false, false, false, "i3-2100T "},
		{false, false, true, false, false, false, "i3-2102 "},
		{false, false, true, false, false, false, "i3-2120 "},
		{false, false, true, false, false, false, "i3-2120T "},
		{false, false, true, false, false, false, "i3-2130 "},
		{false, false, true, false, false, false, "i3-2312M "},
		{false, false, true, false, false, false, "i3-2330E "},
		{false, false, true, false, false, false, "i3-2330M "},
		{false, false, true, false, false, false, "i3-2350M "},
		{false, false, true, false, false, false, "i3-2370M "},
		{false, false, true, false, false, false, "i5-2310 "},
		{false, false, true, false, false, false, "i5-2320 "},
		{false, false, true, false, false, false, "i5-2415M "},
		{false, false, true, false, false, false, "i5-2430M "},
		{false, false, true, false, false, false, "i5-2450M "},
		{false, false, true, false, false, false, "i7-2635QM "},
		{false, false, true, false, false, false, "i7-2670QM "},
		{false, false, true, false, false, false, "i7-2675QM "},
		{false, true, false, false, false, false, "G620 "},
		{false, true, false, false, false, false, "G620T "},
		{false, true, false, false, false, false, "G622 "},
		{false, true, false, false, false, false, "G630 "},
		{false, true, false, false, false, false, "G630T "},
		{false, true, false, false, false, false, "G632 "},
		{false, true, false, false, false, false, "G640 "},
		{false, true, false, false, false, false, "G640T "},
		{false, true, false, false, false, false, "G840 "},
		{false, true, false, false, false, false, "G850 "},
		{false, true, false, false, false, false, "G860 "},
		{false, true, false, false, false, false, "G870 "},
		{false, false, false, false, true, false, "763 "},
		{false, false, false, false, true, false, "925 "},
		{false, false, true, false, false, false, "i3-2357M "},
		{false, false, true, false, false, false, "i3-2310E "},
		{false, false, true, false, false, false, "i3-2340UE "},
		{false, false, true, false, false, false, "i3-2377M "},
		{false, false, true, false, false, false, "i5-2405S "},
		{false, false, true, false, false, false, "i3-2105 "},
		{false, true, false, false, false, false, "B940 "},
		{false, true, false, false, false, false, "B950 "},
		{false, true, false, false, false, false, "957 "},
		{false, false, false, true, false, false, "N570 "},
		{false, false, false, false, true, false, "B810 "},
		{false, false, false, false, true, false, "B810E "},
		{false, false, false, false, true, false, "847E "},
		{false, false, false, false, true, false, "827E "},
		{false, false, false, false, true, false, "847 "},
		{false, false, true, false, false, false, "i5-2467M "},
		{false, false, true, false, false, false, "i7-980 "},
		{false, false, false, false, true, false, "G440 "},
		{false, false, false, true, false, false, "N2600 "},
		{false, false, false, true, false, false, "N2800 "},
		{false, false, true, false, false, false, "i3-2125 "},
		{false, false, false, false, true, false, "B710 "},
		{false, false, false, false, true, false, "B800 "},
		{false, false, false, false, true, false, "787 "},
		{false, false, false, false, true, false, "857 "},
		{false, false, true, false, false, false, "i3-2367M "},
		{false, false, false, false, true, false, "B840 "},
		{false, true, false, false, false, false, "967 "},
		{false, true, false, false, false, false, "B960 "},
		{false, false, true, false, false, false, "i5-2435M "},
		{false, true, false, false, false, false, "350 "},
		{false, false, true, false, false, false, "i7-2700K "},
		{false, false, false, false, true, false, "807UE "},
		{false, false, true, false, false, false, "i7-3960X "},
		{false, false, true, false, false, false, "i7-3930K "},
		{false, false, true, false, false, false, "i7-3820 "},
		{false, false, false, false, true, false, "G460 "},
		{false, true, false, false, false, false, "B970 "},
		{false, true, false, false, false, false, "977 "},
		{false, false, false, false, true, false, "797 "},
		{false, false, false, false, true, false, "867 "},
		{false, false, false, false, true, false, "B815 "},
		{false, false, false, false, true, false, "B720 "},
		{false, false, true, false, false, false, "i5-2450P "},
		{false, false, true, false, false, false, "i5-2380P "},
		{false, false, true, false, false, false, "i7-3610QM "},
		{false, false, true, false, false, false, "i7-3615QM "},
		{false, false, true, false, false, false, "i7-3612QM "},
		{false, false, true, false, false, false, "i5-3330 "},
		{false, false, true, false, false, false, "i5-3330S "},
		{false, false, true, false, false, false, "i5-3450 "},
		{false, false, true, false, false, false, "i5-3450S "},
		{false, false, true, false, false, false, "i5-3570K "},
		{false, false, true, false, false, false, "i7-3770K "},
		{false, true, false, false, false, false, "G2120 "},
		{false, false, true, false, false, false, "i5-2550K "},
		{false, false, true, false, false, false, "i3-3240 "},
		{false, false, true, false, false, false, "i3-3225 "},
		{false, false, true, false, false, false, "i3-3220 "},
		{false, false, true, false, false, false, "i3-3220T "},
		{false, false, true, false, false, false, "i3-3217UE "},
		{false, false, true, false, false, false, "i3-3217U "},
		{false, false, true, false, false, false, "i3-3120ME "},
		{false, false, true, false, false, false, "i3-3110M "},
		{false, false, true, false, false, false, "i5-3317U "},
		{false, false, true, false, false, false, "i5-3210M "},
		{false, false, true, false, false, false, "i7-3517U "},
		{false, true, false, false, false, false, "G2100T "},
		{false, false, true, false, false, false, "i3-3240T "},
		{false, true, false, false, false, false, "G860T "},
		{false, false, false, false, true, false, "877 "},
		{false, false, false, false, true, false, "B820 "},
		{false, true, false, false, false, false, "987 "},
		{false, false, true, false, false, false, "i5-3210M "},
		{false, false, true, false, false, false, "i7-3612QM "},
		{false, false, false, false, true, false, "807 "},
		{false, false, true, false, false, false, "i5-3350P "},
		{false, false, false, false, true, false, "G555 "},
		{false, true, false, false, false, false, "G645 "},
		{false, true, false, false, false, false, "997 "},
		{false, false, false, false, true, false, "887 "},
		{false, false, false, false, true, false, "G465 "},
		{false, true, false, false, false, false, "G645T "},
		{false, true, false, false, false, false, "B980 "},
		{false, false, true, false, false, false, "i3-2365M "},
		{false, false, true, false, false, false, "i7-3970X "},
		{false, false, true, false, false, false, "i3-2328M "},
		{false, true, false, false, false, false, "G2130 "},
		{false, false, true, false, false, false, "i3-3210 "},
		{false, true, false, false, false, false, "G2020T "},
		{false, true, false, false, false, false, "G2020 "},
		{false, true, false, false, false, false, "G2010 "},
		{false, false, false, false, true, false, "G1610 "},
		{false, false, false, false, true, false, "G1620 "},
		{false, false, false, false, true, false, "G1610T "},
		{false, true, false, false, false, false, "G2120T "},
		{false, false, false, false, true, false, "B830 "},
		{false, true, false, false, false, false, "2020M "},
		{false, false, true, false, false, false, "i7-3632QM "},
		{false, false, true, false, false, false, "i7-3630QM "},
		{false, false, true, false, false, false, "i7-3635QM "},
		{false, false, true, false, false, false, "i3-3120M "},
		{false, true, false, false, false, false, "2117U "},
		{false, false, true, false, false, false, "i7-3632QM "},
		{false, false, false, false, true, false, "1020M "},
		{false, false, false, false, true, false, "1037U "},
		{false, false, true, false, false, false, "i3-3229Y "},
		{false, false, true, false, false, false, "i5-3339Y "},
		{false, true, false, false, false, false, "2129Y "},
		{false, false, true, false, false, false, "i7-3537U "},
		{false, false, true, false, false, false, "i5-3337U "},
		{false, false, true, false, false, false, "i5-3230M "},
		{false, false, true, false, false, false, "i3-3227U "},
		{false, false, true, false, false, false, "i3-3130M "},
		{false, true, false, false, false, false, "2030M "},
		{false, false, false, false, true, false, "1000M "},
		{false, false, false, false, true, false, "1007U "},
		{false, false, true, false, false, false, "i5-3230M "},
		{false, false, true, false, false, false, "i3-2375M "},
		{false, false, false, false, true, false, "1020E "},
		{false, false, false, false, true, false, "1047UE "},
		{false, false, false, false, true, false, "927UE "},
		{false, false, false, false, true, false, "G470 "},
		{false, false, true, false, false, false, "i3-2348M "},
		{false, false, true, false, false, false, "i3-3250 "},
		{false, false, true, false, false, false, "i3-3250T "},
		{false, false, true, false, false, false, "i3-3245 "},
		{false, true, false, false, false, false, "G2140 "},
		{false, true, false, false, false, false, "G2030T "},
		{false, true, false, false, false, false, "G2030 "},
		{false, false, true, false, false, false, "i5-4200H "},
		{false, false, true, false, false, false, "i5-4250U "},
		{false, false, true, false, false, false, "i5-4260U "},
		{false, false, true, false, false, false, "i5-4430 "},
		{false, false, true, false, false, false, "i5-4430S "},
		{false, false, true, false, false, false, "i5-4440 "},
		{false, false, true, false, false, false, "i5-4440S "},
		{false, false, true, false, false, false, "i5-4670K "},
		{false, false, false, false, true, false, "1019Y "},
		{false, false, true, false, false, false, "i3-4000M "},
		{false, false, true, false, false, false, "i3-4005U "},
		{false, false, true, false, false, false, "i3-4010U "},
		{false, false, true, false, false, false, "i3-4100U "},
		{false, false, true, false, false, false, "i7-4550U "},
		{false, false, true, false, false, false, "i7-4700HQ "},
		{false, false, true, false, false, false, "i7-4700MQ "},
		{false, false, true, false, false, false, "i7-4702HQ "},
		{false, false, true, false, false, false, "i7-4702MQ "},
		{false, false, true, false, false, false, "i7-4770K "},
		{false, true, false, false, false, false, "2127U "},
		{false, false, false, false, true, false, "1017U "},
		{false, false, false, false, true, false, "1005M "},
		{false, false, true, false, false, false, "i5-4200U "},
		{false, false, true, false, false, false, "i7-4500U "},
		{false, false, false, false, true, false, "2955U "},
		{false, false, true, false, false, false, "i5-4200Y "},
		{false, false, true, false, false, false, "i3-4010Y "},
		{false, false, true, false, false, false, "i3-4158U "},
		{false, false, true, false, false, false, "i5-4258U "},
		{false, false, true, false, false, false, "i5-4288U "},
		{false, false, true, false, false, false, "i7-4558U "},
		{false, false, true, false, false, false, "i3-4100E "},
		{false, false, true, false, false, false, "i3-4102E "},
		{false, false, false, false, true, false, "2000E "},
		{false, false, false, false, true, false, "2002E "},
		{false, false, true, false, false, false, "i5-3340 "},
		{false, false, true, false, false, false, "i5-3340S "},
		{false, false, false, false, true, false, "G1630 "},
		{false, false, false, false, true, false, "G1620T "},
		{false, false, true, false, false, false, "i3-4100M "},
		{false, false, true, false, false, false, "i5-4200M "},
		{false, false, true, false, false, false, "i3-4012Y "},
		{false, false, true, false, false, false, "i3-4020Y "},
		{false, false, true, false, false, false, "i5-4202Y "},
		{false, false, true, false, false, false, "i5-4210Y "},
		{false, false, false, false, true, false, "2980U "},
		{false, true, false, false, false, false, "3556U "},
		{false, true, false, false, false, false, "3560Y "},
		{false, false, true, false, false, false, "i5-4570R "},
		{false, false, true, false, false, false, "i5-4670R "},
		{false, false, true, false, false, false, "i7-4770R "},
		{false, false, false, false, true, false, "2950M "},
		{false, true, false, false, false, false, "3550M "},
		{false, false, true, false, false, false, "i3-4130 "},
		{false, false, true, false, false, false, "i3-4130T "},
		{false, false, true, false, false, false, "i3-4110M "},
		{false, false, true, false, false, false, "i3-4150 "},
		{false, false, true, false, false, false, "i3-4150T "},
		{false, false, true, false, false, false, "i3-4160 "},
		{false, false, true, false, false, false, "i3-4160T "},
		{false, false, true, false, false, false, "i3-4170 "},
		{false, false, true, false, false, false, "i3-4350 "},
		{false, false, true, false, false, false, "i3-4350T "},
		{false, false, true, false, false, false, "i3-4360 "},
		{false, false, true, false, false, false, "i3-4360T "},
		{false, false, true, false, false, false, "i3-4370 "},
		{false, false, true, false, false, false, "i3-4330 "},
		{false, false, true, false, false, false, "i3-4330T "},
		{false, false, true, false, false, false, "i3-4340 "},
		{false, true, false, false, false, false, "G3220 "},
		{false, true, false, false, false, false, "G3220T "},
		{false, true, false, false, false, false, "G3420 "},
		{false, true, false, false, false, false, "G3420T "},
		{false, true, false, false, false, false, "G3430 "},
		{false, false, true, false, false, false, "i3-4330TE "},
		{false, false, true, false, false, false, "i7-4960X "},
		{false, false, true, false, false, false, "i7-4930K "},
		{false, false, true, false, false, false, "i7-4820K "},
		{false, true, false, false, false, false, "G3320TE "},
		{false, true, false, false, false, false, "A1018 "},
		{false, false, false, true, false, false, "E3825 "},
		{false, false, false, true, false, false, "E3845 "},
		{false, false, false, true, false, false, "E3815 "},
		{false, false, false, true, false, false, "E3826 "},
		{false, false, false, true, false, false, "E3827 "},
		{false, false, true, false, false, false, "i5-4460T "},
		{false, false, true, false, false, false, "i5-4210H "},
		{false, false, true, false, false, false, "i7-4710HQ "},
		{false, false, true, false, false, false, "i7-4710MQ "},
		{false, false, true, false, false, false, "i7-4712HQ "},
		{false, false, true, false, false, false, "i7-4712MQ "},
		{false, false, true, false, false, false, "i7-4720HQ "},
		{false, false, true, false, false, false, "i7-4722HQ "},
		{false, false, false, false, true, false, "2957U "},
		{false, false, false, false, true, false, "2961Y "},
		{false, false, false, false, true, false, "2981U "},
		{false, true, false, false, false, false, "3558U "},
		{false, true, false, false, false, false, "3561Y "},
		{false, false, false, false, true, false, "G1830 "},
		{false, false, false, false, true, false, "G1820 "},
		{false, false, false, false, true, false, "G1820T "},
		{false, false, false, false, true, false, "G1820TE "},
		{false, false, true, false, false, false, "i3-4110E "},
		{false, false, true, false, false, false, "i3-4112E "},
		{false, true, false, false, false, false, "G3450 "},
		{false, true, false, false, false, false, "G3450T "},
		{false, true, false, false, false, false, "G3440 "},
		{false, true, false, false, false, false, "G3440T "},
		{false, true, false, false, false, false, "G3240 "},
		{false, true, false, false, false, false, "G3240T "},
		{false, false, false, false, true, false, "G1850 "},
		{false, false, false, false, true, false, "G1840 "},
		{false, false, false, false, true, false, "G1840T "},
		{false, false, true, false, false, false, "i7-4790K "},
		{false, false, true, false, false, false, "i5-4690K "},
		{false, false, true, false, false, false, "i5-4460 "},
		{false, false, true, false, false, false, "i5-4460S "},
		{false, false, true, false, false, false, "i3-4340TE "},
		{false, false, true, false, false, false, "i5-4210M "},
		{false, true, false, false, false, false, "3560M "},
		{false, false, false, false, true, false, "2970M "},
		{false, false, true, false, false, false, "i7-4510U "},
		{false, false, true, false, false, false, "i5-4210U "},
		{false, false, true, false, false, false, "i3-4120U "},
		{false, false, true, false, false, false, "i3-4030U "},
		{false, false, true, false, false, false, "i3-4025U "},
		{false, false, true, false, false, false, "i5-4220Y "},
		{false, false, true, false, false, false, "i3-4030Y "},
		{false, false, true, false, false, false, "i3-4370T "},
		{false, false, true, false, false, false, "i3-4170T "},
		{true, false, false, false, false, false, "E5-2685V3 "},
		{false, true, false, false, false, false, "G3258 "},
		{false, false, true, false, false, false, "i7-5960X "},
		{false, false, true, false, false, false, "i7-5930K "},
		{false, false, true, false, false, false, "i7-5820K "},
		{false, true, false, false, false, false, "G3460 "},
		{false, true, false, false, false, false, "G3460T "},
		{false, false, true, false, false, false, "i7-4578U "},
		{false, false, true, false, false, false, "i5-4308U "},
		{false, false, true, false, false, false, "i5-4278U "},
		{false, true, false, false, false, false, "G3250 "},
		{false, true, false, false, false, false, "G3250T "},
		{false, false, true, false, false, false, "5Y10 "},
		{false, false, true, false, false, false, "5Y10a "},
		{false, false, false, true, false, false, "E3805 "},
		{false, false, true, false, false, false, "5Y31 "},
		{false, false, true, false, false, false, "5Y51 "},
		{false, false, true, false, false, false, "i3-5005U "},
		{false, false, true, false, false, false, "i3-5010U "},
		{false, false, true, false, false, false, "i3-5015U "},
		{false, false, true, false, false, false, "i3-5020U "},
		{false, false, false, false, true, false, "3205U "},
		{false, false, false, false, true, false, "3215U "},
		{false, false, false, false, true, false, "3755U "},
		{false, false, false, false, true, false, "3765U "},
		{false, true, false, false, false, false, "3805U "},
		{false, false, true, false, false, false, "i3-5157U "},
		{false, false, true, false, false, false, "i5-5250U "},
		{false, false, true, false, false, false, "i5-5257U "},
		{false, false, true, false, false, false, "i5-5287U "},
		{false, false, true, false, false, false, "i7-5550U "},
		{false, false, true, false, false, false, "i7-5557U "},
		{false, false, true, false, false, false, "i7-5500U "},
		{false, false, true, false, false, false, "5Y10c "},
		{false, true, false, false, false, false, "3825U "},
		{false, false, false, false, true, false, "N3050 "},
		{false, false, false, false, true, false, "N3150 "},
		{false, false, false, false, true, false, "N3000 "},
		{false, true, false, false, false, false, "N3700 "},
		{false, true, false, false, false, false, "G3260 "},
		{false, true, false, false, false, false, "G3260T "},
		{false, true, false, false, false, false, "G3470 "},
		{false, false, true, false, false, false, "i5-5350H "},
		{false, false, true, false, false, false, "i5-5575R "},
		{false, false, true, false, false, false, "i5-5675R "},
		{false, false, true, false, false, false, "i7-5700HQ "},
		{false, false, true, false, false, false, "i7-5750HQ "},
		{false, false, true, false, false, false, "i7-5775R "},
		{false, false, true, false, false, false, "i7-5850HQ "},
		{false, false, true, false, false, false, "i7-5950HQ "},
		{false, false, true, false, false, false, "i7-5775C "},
		{false, false, true, false, false, false, "i5-5675C "},
		{false, true, false, false, false, false, "G4400 "},
		{false, false, true, false, false, false, "i3-6100U "},
		{false, false, true, false, false, false, "i3-6100TE "},
		{false, false, true, false, false, false, "i5-6400 "},
		{false, false, true, false, false, false, "i5-6400T "},
		{false, false, true, false, false, false, "i5-6600K "},
		{false, false, true, false, false, false, "i5-6200U "},
		{false, false, true, false, false, false, "i7-6500U "},
		{false, false, true, false, false, false, "i7-6700K "},
		{false, false, true, false, false, false, "M3-6Y30 "},
		{false, false, true, false, false, false, "M5-6Y54 "},
		{false, false, true, false, false, false, "i5-6300HQ "},
		{false, false, true, false, false, false, "i7-6700HQ "},
		{false, false, true, false, false, false, "i7-6820HK "},
		{false, false, true, false, false, false, "i3-6100H "},
		{false, true, false, false, false, false, "4405U "},
		{false, true, false, false, false, false, "4405Y "},
		{false, true, false, false, false, false, "G4400TE "},
		{false, false, true, false, false, false, "i3-6100E "},
		{false, false, true, false, false, false, "i3-6102E "},
		{false, true, false, false, false, false, "G4400T "},
		{false, false, false, false, true, false, "G3902E "},
		{false, false, false, false, true, false, "G3900TE "},
		{false, false, false, false, true, false, "G3900E "},
		{false, true, false, false, false, false, "G4500T "},
		{false, false, true, false, false, false, "i3-6300T "},
		{false, false, true, false, false, false, "i3-6100 "},
		{false, true, false, false, false, false, "G4500 "},
		{false, false, true, false, false, false, "i3-6300 "},
		{false, true, false, false, false, false, "G4520 "},
		{false, false, true, false, false, false, "i3-6320 "},
		{false, false, true, false, false, false, "i3-6100T "},
		{false, false, false, false, true, false, "G3920 "},
		{false, false, false, false, true, false, "G3900T "},
		{false, false, false, false, true, false, "G3900 "},
		{false, false, true, false, false, false, "i3-6167U "},
		{false, false, true, false, false, false, "i3-6006U "},
		{false, false, true, false, false, false, "i5-6260U "},
		{false, false, true, false, false, false, "i7-6560U "},
		{false, false, true, false, false, false, "i5-6287U "},
		{false, false, true, false, false, false, "i5-6267U "},
		{false, false, true, false, false, false, "i7-6567U "},
		{false, true, false, false, false, false, "J3710 "},
		{false, false, false, false, true, false, "J3160 "},
		{false, false, false, false, true, false, "J3060 "},
		{false, false, false, false, true, false, "N3010 "},
		{false, true, false, false, false, false, "N3710 "},
		{false, false, false, false, true, false, "N3160 "},
		{false, false, false, false, true, false, "N3060 "},
		{false, false, false, false, true, false, "3855U "},
		{false, false, false, false, true, false, "3955U "},
		{false, false, true, false, false, false, "i5-6402P "},
		{false, false, true, false, false, false, "i5-6350HQ "},
		{false, false, true, false, false, false, "i7-6970HQ "},
		{false, false, true, false, false, false, "i7-6870HQ "},
		{false, false, true, false, false, false, "i7-6770HQ "},
		{false, false, true, false, false, false, "i3-6098P "},
		{false, false, true, false, false, false, "i7-6498DU "},
		{false, false, true, false, false, false, "i5-6198DU "},
		{false, false, true, false, false, false, "i7-6850K "},
		{false, false, true, false, false, false, "i7-6800K "},
		{false, false, true, false, false, false, "i7-6900K "},
		{false, false, true, false, false, false, "i7-6950X "},
		{false, false, true, false, false, false, "i3-7100U "},
		{false, false, true, false, false, false, "i5-7200U "},
		{false, false, true, false, false, false, "M3-7Y30 "},
		{false, false, true, false, false, false, "i7-7500U "},
		{false, false, true, false, false, false, "i5-7Y54 "},
		{false, true, false, false, false, false, "J4205 "},
		{false, true, false, false, false, false, "N4200 "},
		{false, false, false, false, true, false, "J3455 "},
		{false, false, false, false, true, false, "N3450 "},
		{false, false, false, false, true, false, "J3355 "},
		{false, false, false, false, true, false, "N3350 "},
		{false, false, true, false, false, false, "i3-6157U "},
		{false, false, false, true, false, false, "E3940 "},
		{false, false, false, true, false, false, "E3930 "},
		{false, false, false, true, false, false, "E3950 "},
		{false, false, false, false, true, false, "3965U "},
		{false, false, false, false, true, false, "3865U "},
		{false, true, false, false, false, false, "4415U "},
		{false, false, true, false, false, false, "i3-7102E "},
		{false, false, true, false, false, false, "i3-7101TE "},
		{false, false, true, false, false, false, "i3-7100H "},
		{false, false, true, false, false, false, "i3-7101E "},
		{false, false, true, false, false, false, "i3-7100E "},
		{false, true, false, false, false, false, "4410Y "},
		{false, true, false, false, false, false, "G4560 "},
		{false, false, true, false, false, false, "i5-7400 "},
		{false, false, true, false, false, false, "i5-7400T "},
		{false, false, true, false, false, false, "i7-7700HQ "},
		{false, false, false, false, true, false, "G3950 "},
		{false, false, false, false, true, false, "G3930 "},
		{false, true, false, false, false, false, "G4600 "},
		{false, false, true, false, false, false, "i3-7100 "},
		{false, false, true, false, false, false, "i5-7300HQ "},
		{false, false, true, false, false, false, "i3-7300T "},
		{false, false, true, false, false, false, "i3-7300 "},
		{false, true, false, false, false, false, "G4620 "},
		{false, false, true, false, false, false, "i7-7820HK "},
		{false, true, false, false, false, false, "G4560T "},
		{false, false, false, false, true, false, "G3930T "},
		{false, false, true, false, false, false, "i3-7320 "},
		{false, false, true, false, false, false, "i3-7100T "},
		{false, true, false, false, false, false, "G4600T "},
		{false, false, true, false, false, false, "i3-7350K "},
		{false, false, true, false, false, false, "i5-7267U "},
		{false, false, true, false, false, false, "i5-7287U "},
		{false, false, true, false, false, false, "M3-7Y32 "},
		{false, false, true, false, false, false, "i5-7260U "},
		{false, false, true, false, false, false, "i7-7560U "},
		{false, false, true, false, false, false, "i7-7567U "},
		{false, false, true, false, false, false, "i3-7167U "},
		{false, false, true, false, false, false, "i7-8550U "},
		{false, true, false, false, false, false, "4415Y "},
		{false, false, false, false, true, false, "3965Y "},
		{false, false, false, false, true, false, "G3930E "},
		{false, false, false, false, true, false, "G3930TE "},
		{false, false, true, false, false, false, "i5-8250U "},
		{false, false, true, false, false, false, "i3-7130U "},
		{false, false, true, false, false, false, "i5-8400 "},
		{false, false, true, false, false, false, "i3-8100 "},
		{false, false, true, false, false, false, "i3-8350K "},
		{false, false, true, false, false, false, "i7-8709G "},
		{false, false, true, false, false, false, "i5-8305G "},
		{false, false, true, false, false, false, "i7-8809G "},
		{false, false, true, false, false, false, "i7-8705G "},
	}
)

func CPUBlacklistTXTSupport() bool {
	cpuName := api.ProcessorBrandName()

	for i := range TXTUnSupportedCPUs {
		if TXTUnSupportedCPUs[i].xeon && !strings.Contains(cpuName, "Xeon") {
			continue
		}
		if TXTUnSupportedCPUs[i].pentium && !strings.Contains(cpuName, "Pentium") {
			continue
		}
		if TXTUnSupportedCPUs[i].core && !strings.Contains(cpuName, "Core") {
			continue
		}
		if TXTUnSupportedCPUs[i].atom && !strings.Contains(cpuName, "Atom") {
			continue
		}
		if TXTUnSupportedCPUs[i].celeron && !strings.Contains(cpuName, "Celeron") {
			continue
		}
		if TXTUnSupportedCPUs[i].itanium && !strings.Contains(cpuName, "Itanium") {
			continue
		}

		if strings.Contains(cpuName, TXTUnSupportedCPUs[i].name) {
			return true
		}
	}
	return false
}

// CPU Check Whitelist data
type brandNameMetaWl struct {
	xeon    bool
	pentium bool
	core    bool
	name    string
}

// CPU White List
var (
	TXTSupportedCPUs []brandNameMetaWl = []brandNameMetaWl{
		{true, false, false, "3065 "},
		{false, false, true, "E6550 "},
		{false, false, true, "E6750 "},
		{false, false, true, "E6850 "},
		{true, false, false, "L5335 "},
		{false, false, true, "E8200 "},
		{false, false, true, "E8400 "},
		{false, false, true, "E8500 "},
		{false, false, true, "Q9300 "},
		{false, false, true, "Q9450 "},
		{false, false, true, "Q9550 "},
		{false, false, true, "E8190 "},
		{false, false, true, "E8300 "},
		{false, false, true, "Q9400 "},
		{false, false, true, "Q9650 "},
		{false, false, true, "T9400 "},
		{false, false, true, "T9600 "},
		{false, false, true, "P9500 "},
		{false, false, true, "P8600 "},
		{false, false, true, "P8400 "},
		{false, false, true, "E8600 "},
		{false, false, true, "SL9300 "},
		{false, false, true, "SL9400 "},
		{false, false, true, "SP9300 "},
		{false, false, true, "SP9400 "},
		{false, false, true, "SU9300 "},
		{false, false, true, "SU9400 "},
		{false, false, true, "SU3300 "},
		{false, false, true, "T9800 "},
		{false, false, true, "P8700 "},
		{false, false, true, "Q9100 "},
		{false, false, true, "T9550 "},
		{false, false, true, "SU3500 "},
		{false, false, true, "SL9380 "},
		{false, false, true, "SP9600 "},
		{false, false, true, "SL9600 "},
		{false, false, true, "SU9600 "},
		{false, false, true, "P9600 "},
		{false, false, true, "T9900 "},
		{false, false, true, "P8800 "},
		{false, false, true, "Q9000 "},
		{false, false, true, "Q9400S "},
		{false, false, true, "Q9550S "},
		{false, false, true, "i7-870 "},
		{false, false, true, "i7-860 "},
		{false, false, true, "i7-860S "},
		{false, false, true, "P9700 "},
		{false, false, true, "Q9505 "},
		{false, false, true, "Q9505S "},
		{true, false, false, "X3430 "},
		{true, false, false, "X3440 "},
		{true, false, false, "X3450 "},
		{true, false, false, "X3460 "},
		{true, false, false, "X3470 "},
		{false, false, true, "i7-720QM "},
		{false, false, true, "i7-820QM "},
		{false, false, true, "i7-840QM "},
		{false, false, true, "i7-920XM "},
		{false, false, true, "i7-940XM "},
		{true, false, false, "L3426 "},
		{false, false, true, "i5-540M "},
		{false, false, true, "i5-650 "},
		{false, false, true, "i5-660 "},
		{false, false, true, "i5-670 "},
		{false, false, true, "i7-620LM "},
		{false, false, true, "i7-620M "},
		{false, false, true, "i7-620UM "},
		{false, false, true, "i7-640LM "},
		{false, false, true, "i5-520M "},
		{false, false, true, "i5-520UM "},
		{true, false, false, "L3406 "},
		{false, false, true, "i7-640UM "},
		{true, false, false, "X5680 "},
		{true, false, false, "W3680 "},
		{true, false, false, "W3670 "},
		{true, false, false, "X5667 "},
		{true, false, false, "X5670 "},
		{true, false, false, "X5660 "},
		{true, false, false, "X5650 "},
		{true, false, false, "E5640 "},
		{true, false, false, "E5630 "},
		{true, false, false, "E5620 "},
		{true, false, false, "L5640 "},
		{true, false, false, "L5630 "},
		{true, false, false, "L5609 "},
		{true, false, false, "X5677 "},
		{false, false, true, "i7-620LE "},
		{false, false, true, "i7-620UE "},
		{false, false, true, "i5-520E "},
		{false, false, true, "i7-610E "},
		{false, false, true, "i7-870S "},
		{false, false, true, "i7-880 "},
		{true, false, false, "X3480 "},
		{false, false, true, "i5-680 "},
		{true, false, false, "L5638 "},
		{true, false, false, "L5618 "},
		{true, false, false, "E5645 "},
		{false, false, true, "i7-740QM "},
		{false, false, true, "i7-660UM "},
		{false, false, true, "i5-540UM "},
		{false, false, true, "i5-580M "},
		{false, false, true, "i5-560M "},
		{false, false, true, "i7-660LM "},
		{false, false, true, "i7-680UM "},
		{false, false, true, "i5-560UM "},
		{false, false, true, "i7-640M "},
		{false, false, true, "i7-660UE "},
		{false, false, true, "i7-2720QM "},
		{false, false, true, "i5-2540M "},
		{false, false, true, "i5-2400 "},
		{false, false, true, "i5-2400S "},
		{false, false, true, "i5-2500 "},
		{false, false, true, "i5-2500S "},
		{false, false, true, "i5-2500T "},
		{false, false, true, "i7-2600 "},
		{false, false, true, "i7-2600S "},
		{false, false, true, "i7-2820QM "},
		{false, false, true, "i5-2520M "},
		{false, false, true, "i7-2620M "},
		{false, false, true, "i7-2920XM "},
		{true, false, false, "E3-1220 "},
		{true, false, false, "E3-1225 "},
		{true, false, false, "E3-1230 "},
		{true, false, false, "E3-1235 "},
		{true, false, false, "E3-1240 "},
		{true, false, false, "E3-1245 "},
		{true, false, false, "E3-1260L "},
		{true, false, false, "E3-1270 "},
		{true, false, false, "E3-1275 "},
		{true, false, false, "E3-1280 "},
		{true, false, false, "X5690 "},
		{true, false, false, "X5675 "},
		{true, false, false, "X5687 "},
		{true, false, false, "X5672 "},
		{true, false, false, "X5647 "},
		{true, false, false, "E5649 "},
		{true, false, false, "E5607 "},
		{true, false, false, "E5606 "},
		{true, false, false, "E5603 "},
		{true, false, false, "W3690 "},
		{true, false, false, "E3-1220L "},
		{false, false, true, "i5-2390T "},
		{false, false, true, "i5-2510E "},
		{false, false, true, "i7-2640M "},
		{false, false, true, "i7-2710QE "},
		{false, false, true, "i7-2760QM "},
		{false, false, true, "i7-2860QM "},
		{false, false, true, "i7-2960XM "},
		{true, false, false, "E7-2803 "},
		{true, false, false, "E7-4807 "},
		{true, false, false, "E7-2860 "},
		{true, false, false, "E7-4860 "},
		{true, false, false, "E7-8860 "},
		{true, false, false, "E7-2850 "},
		{true, false, false, "E7-4850 "},
		{true, false, false, "E7-8850 "},
		{true, false, false, "E7-8837 "},
		{true, false, false, "E7-8867L "},
		{true, false, false, "E7-2870 "},
		{true, false, false, "E7-4870 "},
		{true, false, false, "E7-8870 "},
		{true, false, false, "E7-2820 "},
		{true, false, false, "E7-2830 "},
		{true, false, false, "E7-4820 "},
		{true, false, false, "E7-4830 "},
		{true, false, false, "E7-8830 "},
		{false, false, true, "i7-2629M "},
		{false, false, true, "i7-2649M "},
		{false, false, true, "i7-2657M "},
		{false, false, true, "i7-2617M "},
		{false, false, true, "i7-2677M "},
		{false, false, true, "i7-2637M "},
		{false, false, true, "i5-2537M "},
		{false, false, true, "i5-2557M "},
		{false, false, true, "i7-2655LE "},
		{false, false, true, "i7-2715QE "},
		{false, false, true, "i7-2610UE "},
		{false, false, true, "i5-2515E "},
		{true, false, false, "E3-1290 "},
		{true, false, false, "E5-2648L "},
		{true, false, false, "E5-2658 "},
		{true, false, false, "E5-2687W "},
		{true, false, false, "E5-2680 "},
		{true, false, false, "E5-2660 "},
		{true, false, false, "E5-2650L "},
		{true, false, false, "E5-2630L "},
		{true, false, false, "E5-2643 "},
		{true, false, false, "E5-2609 "},
		{true, false, false, "E5-2667 "},
		{true, false, false, "E5-2650 "},
		{true, false, false, "E5-2640 "},
		{true, false, false, "E5-2603 "},
		{true, false, false, "E5-2630 "},
		{true, false, false, "E5-2620 "},
		{true, false, false, "E5-2670 "},
		{true, false, false, "E5-2690 "},
		{true, false, false, "E5-2665 "},
		{true, false, false, "E5-2637 "},
		{true, false, false, "E5-1603 "},
		{true, false, false, "E5-1650 "},
		{true, false, false, "E5-4610 "},
		{true, false, false, "E5-4640 "},
		{true, false, false, "E5-4607 "},
		{true, false, false, "E5-4650L "},
		{true, false, false, "E5-4620 "},
		{true, false, false, "E5-4617 "},
		{true, false, false, "E5-4603 "},
		{true, false, false, "E5-2450L "},
		{true, false, false, "E5-2450 "},
		{true, false, false, "E5-2440 "},
		{true, false, false, "E5-2430L "},
		{true, false, false, "E5-2407 "},
		{true, false, false, "E5-2403 "},
		{true, false, false, "E5-2430 "},
		{true, false, false, "E5-2420 "},
		{true, false, false, "E5-1607 "},
		{true, false, false, "E5-1660 "},
		{true, false, false, "E5-1620 "},
		{true, false, false, "E5-4650 "},
		{true, false, false, "E5-2470 "},
		{false, false, true, "i7-3920XM "},
		{false, false, true, "i7-3820QM "},
		{false, false, true, "i7-3720QM "},
		{false, false, true, "i7-3520M "},
		{false, false, true, "i5-3360M "},
		{false, false, true, "i5-3320M "},
		{false, false, true, "i7-3667U "},
		{false, false, true, "i5-3427U "},
		{false, false, true, "i5-3475S "},
		{false, false, true, "i5-3550 "},
		{false, false, true, "i5-3550S "},
		{false, false, true, "i5-3570T "},
		{false, false, true, "i7-3770S "},
		{false, false, true, "i7-3770T "},
		{false, false, true, "i5-3570S "},
		{false, false, true, "i5-3570 "},
		{false, false, true, "i5-3470T "},
		{false, false, true, "i5-3610ME "},
		{false, false, true, "i7-3615QE "},
		{false, false, true, "i7-3612QE "},
		{false, false, true, "i7-3610QE "},
		{false, false, true, "i7-3555LE "},
		{false, false, true, "i7-3517UE "},
		{false, false, true, "i7-3770 "},
		{true, false, false, "E3-1290V2 "},
		{true, false, false, "E3-1280V2 "},
		{true, false, false, "E3-1275V2 "},
		{true, false, false, "E3-1270V2 "},
		{true, false, false, "E3-1265LV2 "},
		{true, false, false, "E3-1245V2 "},
		{true, false, false, "E3-1240V2 "},
		{true, false, false, "E3-1230V2 "},
		{true, false, false, "E3-1225V2 "},
		{true, false, false, "E3-1220V2 "},
		{true, false, false, "E3-1220LV2 "},
		{false, true, false, "1405 "},
		{true, false, false, "E5-1428L "},
		{true, false, false, "E5-2448L "},
		{true, false, false, "E5-2428L "},
		{true, false, false, "E5-2418L "},
		{false, true, false, "1403 "},
		{false, true, false, "1407 "},
		{true, false, false, "E5-1410 "},
		{false, false, true, "i5-3470S "},
		{false, false, true, "i5-3470 "},
		{true, false, false, "E3-1125C "},
		{true, false, false, "E3-1105C "},
		{false, false, true, "i3-2115C "},
		{false, true, false, "B915C "},
		{false, false, false, "725C "},
		{false, false, true, "i7-3840QM "},
		{false, false, true, "i7-3740QM "},
		{false, false, true, "i7-3940XM "},
		{false, false, true, "i7-3540M "},
		{false, false, true, "i5-3380M "},
		{false, false, true, "i5-3340M "},
		{false, false, true, "i7-3687U "},
		{false, false, true, "i5-3437U "},
		{false, false, true, "i5-3439Y "},
		{false, false, true, "i7-3689Y "},
		{false, false, true, "i5-4350U "},
		{false, false, true, "i5-4360U "},
		{false, false, true, "i5-4570 "},
		{false, false, true, "i5-4570S "},
		{false, false, true, "i5-4570T "},
		{false, false, true, "i5-4670 "},
		{false, false, true, "i5-4670S "},
		{false, false, true, "i5-4670T "},
		{true, false, false, "E3-1220LV3 "},
		{true, false, false, "E3-1220 v3 "},
		{true, false, false, "E3-1230Lv3 "},
		{true, false, false, "E3-1230 v3 "},
		{true, false, false, "E3-1240 v3 "},
		{true, false, false, "E3-1270 v3 "},
		{true, false, false, "E3-1280 v3 "},
		{false, false, true, "i7-4650U "},
		{false, false, true, "i7-4765T "},
		{false, false, true, "i7-4770 "},
		{false, false, true, "i7-4770S "},
		{false, false, true, "i7-4770T "},
		{false, false, true, "i7-4800MQ "},
		{false, false, true, "i7-4900MQ "},
		{false, false, true, "i7-4930MX "},
		{true, false, false, "E7-2850V2 "},
		{true, false, false, "E7-2870V2 "},
		{true, false, false, "E7-2880V2 "},
		{true, false, false, "E7-2890V2 "},
		{true, false, false, "E7-4809V2 "},
		{true, false, false, "E7-4820V2 "},
		{true, false, false, "E7-4830V2 "},
		{true, false, false, "E7-4850V2 "},
		{true, false, false, "E7-4860V2 "},
		{true, false, false, "E7-4870V2 "},
		{true, false, false, "E7-4890V2 "},
		{true, false, false, "E7-8850V2 "},
		{true, false, false, "E7-8857V2 "},
		{true, false, false, "E7-8870V2 "},
		{true, false, false, "E7-8880LV2 "},
		{true, false, false, "E7-8880V2 "},
		{true, false, false, "E7-8890V2 "},
		{true, false, false, "E7-8891V2 "},
		{true, false, false, "E7-8893V2 "},
		{true, false, false, "E5-2440V2 "},
		{true, false, false, "E5-2450V2 "},
		{true, false, false, "E5-2450LV2 "},
		{true, false, false, "E5-2470V2 "},
		{true, false, false, "E5-2640V2 "},
		{true, false, false, "E5-2643V2 "},
		{true, false, false, "E5-2650V2 "},
		{true, false, false, "E5-2650LV2 "},
		{true, false, false, "E5-2660V2 "},
		{true, false, false, "E5-2667V2 "},
		{true, false, false, "E5-2670V2 "},
		{true, false, false, "E5-2680V2 "},
		{true, false, false, "E5-2690V2 "},
		{true, false, false, "E5-2695V2 "},
		{true, false, false, "E5-2697V2 "},
		{true, false, false, "E5-4610V2 "},
		{true, false, false, "E5-4620V2 "},
		{true, false, false, "E5-4627V2 "},
		{true, false, false, "E5-4640V2 "},
		{true, false, false, "E5-4650V2 "},
		{true, false, false, "E5-4657LV2 "},
		{true, false, false, "E3-1225V3 "},
		{true, false, false, "E3-1245 v3 "},
		{true, false, false, "E3-1265Lv3 "},
		{true, false, false, "E3-1275 v3 "},
		{true, false, false, "E3-1285 v3 "},
		{true, false, false, "E3-1285Lv3 "},
		{true, false, false, "E3-1268LV3 "},
		{false, false, true, "i5-4570TE "},
		{false, false, true, "i7-4700EQ "},
		{false, false, true, "i5-4402EC "},
		{false, false, true, "i7-4700EC "},
		{false, false, true, "i7-4702EC "},
		{false, false, true, "i7-4770TE "},
		{true, false, false, "E7-4880V2 "},
		{true, false, false, "E5-1410V2 "},
		{true, false, false, "E5-1428LV2 "},
		{true, false, false, "E5-1620V2 "},
		{true, false, false, "E5-1650V2 "},
		{true, false, false, "E5-1660V2 "},
		{true, false, false, "E5-2407V2 "},
		{true, false, false, "E5-2418LV2 "},
		{true, false, false, "E5-2420V2 "},
		{true, false, false, "E5-2430V2 "},
		{true, false, false, "E5-2430LV2 "},
		{true, false, false, "E5-2609V2 "},
		{true, false, false, "E5-2618LV2 "},
		{true, false, false, "E5-2620V2 "},
		{true, false, false, "E5-2630V2 "},
		{true, false, false, "E5-2630LV2 "},
		{true, false, false, "E5-2637V2 "},
		{true, false, false, "E5-4603V2 "},
		{true, false, false, "E5-4607V2 "},
		{true, false, false, "E5-2448LV2 "},
		{true, false, false, "E5-2428LV2 "},
		{true, false, false, "E5-2403V2 "},
		{false, false, true, "i7-4950HQ "},
		{false, false, true, "i7-4850HQ "},
		{false, false, true, "i7-4750HQ "},
		{false, false, true, "i7-4960HQ "},
		{false, false, true, "i7-4860HQ "},
		{false, false, true, "i7-4760HQ "},
		{true, false, false, "E5-2603V2 "},
		{true, false, false, "E5-2628LV2 "},
		{true, false, false, "E5-2648LV2 "},
		{true, false, false, "E5-2658V2 "},
		{true, false, false, "E5-2687WV2 "},
		{false, false, true, "i5-4400E "},
		{false, false, true, "i7-4701EQ "},
		{false, false, true, "i7-4860EQ "},
		{false, false, true, "i7-4850EQ "},
		{true, false, false, "E3-1275LV3 "},
		{false, false, true, "i5-4402E "},
		{false, false, true, "i5-4300U "},
		{false, false, true, "i5-4300M "},
		{false, false, true, "i7-4600M "},
		{true, false, false, "E5-4624LV2 "},
		{false, false, true, "i5-4300Y "},
		{false, false, true, "i5-4302Y "},
		{false, false, true, "i7-4600U "},
		{false, false, true, "i7-4610Y "},
		{false, false, true, "i5-4330M "},
		{false, false, true, "i7-4771 "},
		{true, false, false, "E5-1607V2 "},
		{true, false, false, "E5-1680V2 "},
		{false, true, false, "1405V2 "},
		{false, true, false, "1403V2 "},
		{true, false, false, "E3-1105CV2 "},
		{true, false, false, "E3-1125CV2 "},
		{false, true, false, "B925C "},
		{false, false, true, "i3-3115C "},
		{true, false, false, "E3-1135CV2 "},
		{false, false, true, "i5-4590T "},
		{false, false, true, "i7-4810MQ "},
		{false, false, true, "i7-4910MQ "},
		{false, false, true, "i7-4940MX "},
		{false, false, true, "i5-4410E "},
		{false, false, true, "i5-4422E "},
		{true, false, false, "E7-8895V2 "},
		{true, false, false, "E3-1284LV3 "},
		{true, false, false, "E5-2673V2 "},
		{false, false, true, "i5-4310U "},
		{false, false, true, "i5-4340M "},
		{false, false, true, "i7-4610M "},
		{false, false, true, "i5-4310M "},
		{false, false, true, "i7-4790 "},
		{false, false, true, "i7-4790S "},
		{false, false, true, "i7-4790T "},
		{false, false, true, "i5-4690 "},
		{false, false, true, "i5-4690S "},
		{false, false, true, "i5-4690T "},
		{false, false, true, "i7-4785T "},
		{false, false, true, "i5-4590 "},
		{false, false, true, "i5-4590S "},
		{true, false, false, "E3-1281V3 "},
		{true, false, false, "E3-1271V3 "},
		{true, false, false, "E3-1241V3 "},
		{true, false, false, "E3-1231V3 "},
		{true, false, false, "E3-1240LV3 "},
		{true, false, false, "E3-1286V3 "},
		{true, false, false, "E3-1286LV3 "},
		{true, false, false, "E3-1276V3 "},
		{true, false, false, "E3-1246V3 "},
		{true, false, false, "E3-1226V3 "},
		{true, false, false, "E5-2683V3 "},
		{true, false, false, "E5-2695V3 "},
		{true, false, false, "E5-2697V3 "},
		{true, false, false, "E5-2698V3 "},
		{true, false, false, "E5-2699V3 "},
		{true, false, false, "E5-2628LV3 "},
		{true, false, false, "E5-2650V3 "},
		{true, false, false, "E5-2660V3 "},
		{true, false, false, "E5-2670V3 "},
		{true, false, false, "E5-2690V3 "},
		{true, false, false, "E5-2609V3 "},
		{true, false, false, "E5-2643V3 "},
		{true, false, false, "E5-2648LV3 "},
		{true, false, false, "E5-2650LV3 "},
		{true, false, false, "E5-2658V3 "},
		{true, false, false, "E5-2680V3 "},
		{true, false, false, "E5-2687WV3 "},
		{true, false, false, "E5-1603V3 "},
		{true, false, false, "E5-1607V3 "},
		{true, false, false, "E5-1620V3 "},
		{true, false, false, "E5-1630V3 "},
		{true, false, false, "E5-1650V3 "},
		{true, false, false, "E5-1660V3 "},
		{true, false, false, "E5-1680V3 "},
		{true, false, false, "E5-2603V3 "},
		{true, false, false, "E5-2608LV3 "},
		{true, false, false, "E5-2618LV3 "},
		{true, false, false, "E5-2620V3 "},
		{true, false, false, "E5-2623V3 "},
		{true, false, false, "E5-2630V3 "},
		{true, false, false, "E5-2630LV3 "},
		{true, false, false, "E5-2637V3 "},
		{true, false, false, "E5-2640V3 "},
		{true, false, false, "E5-2667V3 "},
		{false, false, true, "i7-4980HQ "},
		{false, false, true, "i7-4870HQ "},
		{false, false, true, "i7-4770HQ "},
		{false, false, true, "5Y70 "},
		{true, false, false, "E5-1428LV3 "},
		{true, false, false, "E5-2408LV3 "},
		{true, false, false, "E5-2418LV3 "},
		{true, false, false, "E5-2428LV3 "},
		{true, false, false, "E5-2438LV3 "},
		{false, false, true, "5Y71 "},
		{true, false, false, "E7-4809V3 "},
		{true, false, false, "E7-4820V3 "},
		{true, false, false, "E7-4830V3 "},
		{true, false, false, "E7-4850V3 "},
		{true, false, false, "E7-8860V3 "},
		{true, false, false, "E7-8867V3 "},
		{true, false, false, "E7-8870V3 "},
		{true, false, false, "E7-8880V3 "},
		{true, false, false, "E7-8880LV3 "},
		{true, false, false, "E7-8890V3 "},
		{true, false, false, "E7-8891V3 "},
		{true, false, false, "E7-8893V3 "},
		{true, false, false, "E7-8895V3 "},
		{false, false, true, "i5-5350U "},
		{false, false, true, "i7-5650U "},
		{false, false, true, "i5-5300U "},
		{false, false, true, "i7-5600U "},
		{true, false, false, "E5-4610V3 "},
		{true, false, false, "E5-4620V3 "},
		{true, false, false, "E5-4627V3 "},
		{true, false, false, "E5-4640V3 "},
		{true, false, false, "E5-4648V3 "},
		{true, false, false, "E5-4650V3 "},
		{true, false, false, "E5-4655V3 "},
		{true, false, false, "E5-4660V3 "},
		{true, false, false, "E5-4667V3 "},
		{true, false, false, "E5-4669V3 "},
		{true, false, false, "E5-2658AV3 "},
		{true, false, false, "D-1520 "},
		{true, false, false, "D-1540 "},
		{true, false, false, "E3-1270LV4 "},
		{true, false, false, "E3-1265LV4 "},
		{true, false, false, "E3-1285LV4 "},
		{true, false, false, "E3-1284LV4 "},
		{true, false, false, "E3-1285V4 "},
		{false, false, true, "i7-5700EQ "},
		{false, false, true, "i7-5850EQ "},
		{true, false, false, "E3-1258LV4 "},
		{true, false, false, "E3-1278LV4 "},
		{true, false, false, "E3-1225V5 "},
		{true, false, false, "E3-1240LV5 "},
		{true, false, false, "E3-1235LV5 "},
		{true, false, false, "E3-1280V5 "},
		{true, false, false, "E3-1220V5 "},
		{true, false, false, "E3-1245V5 "},
		{true, false, false, "E3-1270V5 "},
		{true, false, false, "E3-1260LV5 "},
		{true, false, false, "E3-1240V5 "},
		{true, false, false, "E3-1275V5 "},
		{true, false, false, "E3-1268LV5 "},
		{true, false, false, "E3-1230V5 "},
		{false, false, true, "i5-6500T "},
		{false, false, true, "i5-6500 "},
		{false, false, true, "i5-6500TE "},
		{false, false, true, "i5-6600 "},
		{false, false, true, "i5-6600T "},
		{false, false, true, "i5-6300U "},
		{false, false, true, "i7-6600U "},
		{false, false, true, "i7-6700 "},
		{false, false, true, "M5-6Y57 "},
		{false, false, true, "M7-6Y75 "},
		{false, false, true, "i7-6700T "},
		{false, false, true, "i7-6700TE "},
		{false, false, true, "i5-6440HQ "},
		{false, false, true, "i7-6820HQ "},
		{false, false, true, "i7-6920HQ "},
		{true, false, false, "E3-1505MV5 "},
		{true, false, false, "E3-1535MV5 "},
		{false, false, true, "i5-6440EQ "},
		{false, false, true, "i7-6820EQ "},
		{false, false, true, "i7-6822EQ "},
		{false, false, true, "i5-6442EQ "},
		{true, false, false, "E3-1505LV5 "},
		{false, false, true, "i5-6360U "},
		{false, false, true, "i7-6660U "},
		{true, false, false, "D-1529 "},
		{true, false, false, "D-1527 "},
		{true, false, false, "D-1537 "},
		{true, false, false, "D-1528 "},
		{true, false, false, "D-1541 "},
		{true, false, false, "D-1539 "},
		{true, false, false, "D-1518 "},
		{true, false, false, "D-1521 "},
		{true, false, false, "D-1531 "},
		{true, false, false, "D-1548 "},
		{true, false, false, "E5-2695V4 "},
		{true, false, false, "E5-2699V4 "},
		{false, false, true, "i7-6650U "},
		{false, true, false, "D1517 "},
		{false, true, false, "D1508 "},
		{false, true, false, "D1519 "},
		{false, true, false, "D1509 "},
		{false, true, false, "D1507 "},
		{true, false, false, "E5-2687WV4 "},
		{true, false, false, "E5-2679V4 "},
		{true, false, false, "E5-2650LV4 "},
		{true, false, false, "E5-2698V4 "},
		{true, false, false, "E5-2680V4 "},
		{true, false, false, "E5-2697V4 "},
		{true, false, false, "E5-2648LV4 "},
		{true, false, false, "E5-2683V4 "},
		{true, false, false, "E5-2650V4 "},
		{true, false, false, "E5-2697AV4 "},
		{true, false, false, "E5-2689V4 "},
		{true, false, false, "E5-2690V4 "},
		{true, false, false, "E5-2658V4 "},
		{true, false, false, "E5-2660V4 "},
		{true, false, false, "E5-2628LV4 "},
		{true, false, false, "E5-2630LV4 "},
		{true, false, false, "E5-2667V4 "},
		{true, false, false, "E5-2623V4 "},
		{true, false, false, "E5-2630V4 "},
		{true, false, false, "E5-2618LV4 "},
		{true, false, false, "E5-2637V4 "},
		{true, false, false, "E5-2640V4 "},
		{true, false, false, "E5-1660V4 "},
		{true, false, false, "E5-2620V4 "},
		{true, false, false, "E5-1630V4 "},
		{true, false, false, "E5-2608LV4 "},
		{true, false, false, "E5-2643V4 "},
		{true, false, false, "E5-2609V4 "},
		{true, false, false, "E5-1620V4 "},
		{true, false, false, "E5-1680V4 "},
		{true, false, false, "E5-2603V4 "},
		{true, false, false, "E5-1650V4 "},
		{true, false, false, "E5-1603V4 "},
		{true, false, false, "E5-1607V4 "},
		{false, false, true, "i5-6585R "},
		{false, false, true, "i5-6685R "},
		{false, false, true, "i7-6785R "},
		{true, false, false, "D-1559 "},
		{true, false, false, "D-1577 "},
		{true, false, false, "E3-1575MV5 "},
		{true, false, false, "D-1571 "},
		{true, false, false, "D-1567 "},
		{true, false, false, "D-1581 "},
		{true, false, false, "E3-1515MV5 "},
		{true, false, false, "E3-1545MV5 "},
		{true, false, false, "D-1557 "},
		{true, false, false, "D-1587 "},
		{true, false, false, "E3-1565LV5 "},
		{true, false, false, "E3-1585LV5 "},
		{true, false, false, "E3-1585V5 "},
		{true, false, false, "E7-8890V4 "},
		{true, false, false, "E7-8893V4 "},
		{true, false, false, "E7-8880V4 "},
		{true, false, false, "E7-8860V4 "},
		{true, false, false, "E7-4809V4 "},
		{true, false, false, "E7-8891V4 "},
		{true, false, false, "E5-4660V4 "},
		{true, false, false, "E5-4640V4 "},
		{true, false, false, "E5-4627V4 "},
		{true, false, false, "E5-4620V4 "},
		{true, false, false, "E7-8870V4 "},
		{true, false, false, "E5-4628LV4 "},
		{true, false, false, "E7-8867V4 "},
		{true, false, false, "E5-4669V4 "},
		{true, false, false, "E7-4850V4 "},
		{true, false, false, "E5-4667V4 "},
		{true, false, false, "E5-4655V4 "},
		{true, false, false, "E5-4650V4 "},
		{true, false, false, "E7-4830V4 "},
		{true, false, false, "E5-4610V4 "},
		{true, false, false, "E7-4820V4 "},
		{true, false, false, "E3-1558LV5 "},
		{true, false, false, "E3-1578LV5 "},
		{true, false, false, "E7-8855V4 "},
		{false, false, true, "i7-7Y75 "},
		{true, false, false, "E5-2699AV4 "},
		{true, false, false, "E7-8894V4 "},
		{true, false, false, "E5-2699RV4 "},
		{false, false, true, "i5-7500T "},
		{false, false, true, "i7-7700T "},
		{false, false, true, "i5-7500 "},
		{false, false, true, "i7-7820EQ "},
		{false, false, true, "i7-7700 "},
		{false, false, true, "i5-7600 "},
		{false, false, true, "i5-7600T "},
		{false, false, true, "i5-7440HQ "},
		{false, false, true, "i5-7Y57 "},
		{false, false, true, "i7-7920HQ "},
		{true, false, false, "E3-1505MV6 "},
		{false, false, true, "i7-7600U "},
		{true, false, false, "E3-1535MV6 "},
		{true, false, false, "E3-1240V6 "},
		{true, false, false, "E3-1220V6 "},
		{true, false, false, "E3-1205V6 "},
		{false, false, true, "i5-7300U "},
		{true, false, false, "E3-1245V6 "},
		{true, false, false, "E3-1230V6 "},
		{true, false, false, "E3-1280V6 "},
		{true, false, false, "E3-1225V6 "},
		{true, false, false, "E3-1275V6 "},
		{true, false, false, "E3-1270V6 "},
		{false, false, true, "i7-7820HQ "},
		{false, false, true, "i5-7440EQ "},
		{false, false, true, "i5-7442EQ "},
		{false, false, true, "i5-7360U "},
		{false, false, true, "i7-7660U "},
		{true, false, false, "E3-1505LV6 "},
		{true, false, false, "E3-1285V6 "},
		{true, false, false, "5118 "},
		{true, false, false, "5120 "},
		{true, false, false, "5122 "},
		{true, false, false, "6138 "},
		{true, false, false, "5120T "},
		{true, false, false, "6136 "},
		{true, false, false, "4116 "},
		{true, false, false, "6128 "},
		{true, false, false, "6126 "},
		{true, false, false, "5115 "},
		{true, false, false, "6140 "},
		{true, false, false, "6140M "},
		{true, false, false, "6142 "},
		{true, false, false, "6142M "},
		{true, false, false, "6148 "},
		{true, false, false, "6150 "},
		{true, false, false, "6152 "},
		{true, false, false, "6130 "},
		{true, false, false, "6134 "},
		{true, false, false, "6134M "},
		{true, false, false, "6154 "},
		{true, false, false, "8180 "},
		{true, false, false, "8153 "},
		{true, false, false, "8180M "},
		{true, false, false, "8156 "},
		{true, false, false, "8158 "},
		{true, false, false, "8160 "},
		{true, false, false, "8160M "},
		{true, false, false, "8164 "},
		{true, false, false, "8168 "},
		{true, false, false, "8176M "},
		{true, false, false, "8170 "},
		{true, false, false, "8170M "},
		{true, false, false, "8176 "},
		{true, false, false, "5117 "},
		{true, false, false, "E3-1501MV6 "},
		{true, false, false, "E3-1501LV6 "},
		{true, false, false, "D-1533N "},
		{true, false, false, "D-1513N "},
		{true, false, false, "D-1543N "},
		{true, false, false, "D-1523N "},
		{true, false, false, "D-1553N "},
		{true, false, false, "3106 "},
		{true, false, false, "6132 "},
		{true, false, false, "6138T "},
		{true, false, false, "8160T "},
		{true, false, false, "4108 "},
		{true, false, false, "6130T "},
		{true, false, false, "3104 "},
		{true, false, false, "4110 "},
		{true, false, false, "6126T "},
		{true, false, false, "4109T "},
		{true, false, false, "4114 "},
		{true, false, false, "4112 "},
		{true, false, false, "6142F "},
		{true, false, false, "6138F "},
		{true, false, false, "8160F "},
		{true, false, false, "6130F "},
		{true, false, false, "6126F "},
		{true, false, false, "6148F "},
		{true, false, false, "6146 "},
		{true, false, false, "6144 "},
		{true, false, false, "5117F "},
		{false, false, true, "i7-8650U "},
		{false, false, true, "i5-8350U "},
		{true, false, false, "W-2123 "},
		{true, false, false, "W-2102 "},
		{true, false, false, "W-2104 "},
		{true, false, false, "W-2133 "},
		{true, false, false, "W-2155 "},
		{true, false, false, "8176F "},
		{true, false, false, "4114T "},
		{true, false, false, "5119T "},
		{true, false, false, "4116T "},
		{false, false, true, "i7-8700K "},
		{false, false, true, "i5-8600K "},
		{false, false, true, "i7-8700 "},
		{true, false, false, "W-2145 "},
		{true, false, false, "W-2125 "},
		{true, false, false, "W-2135 "},
		{true, false, false, "W-2195 "},
		{true, false, false, "W-2175 "},
		{false, false, true, "i7-8706G "},
	}
)

func CPUWhitelistTXTSupport() bool {
	cpuName := api.ProcessorBrandName()

	for i := range TXTSupportedCPUs {
		if TXTSupportedCPUs[i].xeon && !strings.Contains(cpuName, "Xeon") {
			continue
		}
		if TXTSupportedCPUs[i].pentium && !strings.Contains(cpuName, "Pentium") {
			continue
		}
		if TXTSupportedCPUs[i].core && !strings.Contains(cpuName, "Core") {
			continue
		}
		if strings.Contains(cpuName, TXTSupportedCPUs[i].name) {
			return true
		}
	}
	return false
}

// TPM NVRAM TXT Adresses
const (
	psIndex  = 0x50000001
	auxIndex = 0x50000003
)

type TestResult int
type TestStatus int
type TXTSpec int

const (
	ResultNotRun TestResult = iota
	ResultDependencyFailed
	ResultInternalError
	ResultFail
	ResultPass
)

const (
	TestImplemented TestStatus = iota
	TestNotImplemented
	TestPartlyImplemented
)
const (
	TXT TXTSpec = iota
	CBnT
	Common
)

func (t TXTSpec) String() string {
	return [...]string{"TXT", "CBnT", "Common"}[t]
}
func (t TestStatus) String() string {
	return [...]string{"Implemented", "Not implemented", "Partly implemented"}[t]
}
func (t TestResult) String() string {
	return [...]string{"TESTNOTRUN", "DEPENDENCY_FAILED", "INTERNAL_ERROR", "FAIL", "PASS"}[t]
}

type Test struct {
	Name     string
	Required bool
	//testerror: If test fails and returns an testerror -> test failure
	//internalerror: If test fails and returns an internalerror
	//-> mostly api errors, but not directly testrelated problem.
	//The return call in test functions shall return only one of the errors,
	//while the other is nil.
	function     func() (bool, error, error)
	Result       TestResult
	dependencies []*Test
	ErrorText    string
	Status       TestStatus
	Spec         TXTSpec
}

func (self *Test) Run() bool {

	// Now run the test itself
	rc, testerror, internalerror := self.function()
	if internalerror != nil && testerror == nil {
		self.Result = ResultInternalError
		self.ErrorText = internalerror.Error()
	} else if testerror != nil && internalerror == nil {
		self.ErrorText = testerror.Error()
		self.Result = ResultFail
	} else if rc {
		self.Result = ResultPass
	} else {
		self.Result = ResultFail
	}

	return self.Result == ResultPass
}
